services:
  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - collaborative_activity_tracker_network

  db:
    image: postgres:15
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - collaborative_activity_tracker_network

volumes:
  postgres_data:

networks:
  collaborative_activity_tracker_network:
